### ISSUE TITLE
Problems when run cLoops2 callLoops with -p

### ISSUE THREAD

**Issue by YiyangZhangPKU** [YaqiangCao/cLoops2#17]
Hello!

When I ran cLoops callLoops on my Data, I found if I set -p to any number except 1, it raise such a error:
```
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/joblib/_utils.py", line 72, in __call__
    return self.func(**kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/joblib/parallel.py", line 607, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/cLoops2/callCisLoops.py", line 86, in runCisDBSCANLoops
    logger.info(report)
    ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'info'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Volumes/Lexar/Applications/miniconda3/envs/test/bin/cLoops2", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/cLoops2/cLoops2.py", line 3679, in main
    callCisLoops(
  File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/cLoops2/callCisLoops.py", line 557, in callCisLoops
    loops_2, dis_2, dss_2 = parallelRunCisDBSCANLoops(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/cLoops2/callCisLoops.py", line 139, in parallelRunCisDBSCANLoops
    ds = Parallel(n_jobs=cpu,backend="multiprocessing")(delayed(runCisDBSCANLoops)(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/joblib/parallel.py", line 2072, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/joblib/parallel.py", line 1682, in _get_outputs
    yield from self._retrieve()
  File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/joblib/parallel.py", line 1784, in _retrieve
    self._raise_error_fast()
  File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/joblib/parallel.py", line 1859, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/joblib/parallel.py", line 758, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/joblib/parallel.py", line 773, in _return_or_raise
    raise self._result
AttributeError: 'NoneType' object has no attribute 'info'
```

It seems something went wrong with logger variable, but I have no idea what the problem is exactly, and running other subcommand with -p do not raise any error.

I found that two global variables: 'logger' and 'DBSCAN', to be NONE when runCisDBSCANLoops function is called by Parallel. I'm using joblib 1.5.1, is this the cause of the problem?

Thanks!

**Comment by YaqiangCao** [comment]
> Hello!
> 
> When I ran cLoops callLoops on my Data, I found if I set -p to any number except 1, it raise such a error:
> 
> ```
> joblib.externals.loky.process_executor._RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/joblib/_utils.py", line 72, in __call__
>     return self.func(**kwargs)
>            ^^^^^^^^^^^^^^^^^^^
>   File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/joblib/parallel.py", line 607, in __call__
>     return [func(*args, **kwargs) for func, args, kwargs in self.items]
>             ^^^^^^^^^^^^^^^^^^^^^
>   File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/cLoops2/callCisLoops.py", line 86, in runCisDBSCANLoops
>     logger.info(report)
>     ^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'info'
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Volumes/Lexar/Applications/miniconda3/envs/test/bin/cLoops2", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/cLoops2/cLoops2.py", line 3679, in main
>     callCisLoops(
>   File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/cLoops2/callCisLoops.py", line 557, in callCisLoops
>     loops_2, dis_2, dss_2 = parallelRunCisDBSCANLoops(
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/cLoops2/callCisLoops.py", line 139, in parallelRunCisDBSCANLoops
>     ds = Parallel(n_jobs=cpu,backend="multiprocessing")(delayed(runCisDBSCANLoops)(
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/joblib/parallel.py", line 2072, in __call__
>     return output if self.return_generator else list(output)
>                                                 ^^^^^^^^^^^^
>   File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/joblib/parallel.py", line 1682, in _get_outputs
>     yield from self._retrieve()
>   File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/joblib/parallel.py", line 1784, in _retrieve
>     self._raise_error_fast()
>   File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/joblib/parallel.py", line 1859, in _raise_error_fast
>     error_job.get_result(self.timeout)
>   File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/joblib/parallel.py", line 758, in get_result
>     return self._return_or_raise()
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Volumes/Lexar/Applications/miniconda3/envs/test/lib/python3.12/site-packages/joblib/parallel.py", line 773, in _return_or_raise
>     raise self._result
> AttributeError: 'NoneType' object has no attribute 'info'
> ```
> 
> It seems something went wrong with logger variable, but I have no idea what the problem is exactly, and running other subcommand with -p do not raise any error.
> 
> I found that two global variables: 'logger' and 'DBSCAN', to be NONE when runCisDBSCANLoops function is called by Parallel. I'm using joblib 1.5.1, is this the cause of the problem?
> 
> Thanks!

Hi Yiyang,
     It seems a bug from joblib, how about install it with joblib=0.16.0=py_0? 
     In lines 496-504 (https://github.com/YaqiangCao/cLoops2/blob/master/cLoops2/callCisLoops.py#L135) defined log and DBSCAN, they should not be None. 
Best,
Yaqiang

**Comment by YiyangZhangPKU** [comment]
Hello!

Sorry for late reply. I tested several versions of joblib, and found using old version of joblib such as  0.16.0 raises a new error, it seems not work well with python version I use(3.12). While newer versions of joblib raise the same error. A completely new virtual environment may work, but personally I just modified several lines of code to make it the code work. I think newer version of Python and(or) joblib treat global variables differently and they are not correctly accessible to functions in  Parallel. 

Thanks!

**Comment by YaqiangCao** [comment]
Hi Yiyang, 
    Thanks for the updates. 
Best,
Yaqiang
